-- ============================================
-- 05_create_users_and_security.sql
-- Create users, assign roles and schema permissions
--
-- CI/CD-safe: uses Entra ID groups only
-- No hardcoded personal users
--
-- Run order: After 04_create_triggers.sql
-- Can be run multiple times safely (idempotent)
--
-- NOTE: Commented out - Fabric SQL Database does not support
-- CREATE USER FROM EXTERNAL PROVIDER for Entra ID groups
-- without Managed Identity configuration.
-- Access is managed via Fabric workspace roles instead.
-- ============================================

-- Security group: sg-av-engineers
-- IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'sg-av-engineers')
--     CREATE USER [sg-av-engineers] FROM EXTERNAL PROVIDER
-- GO
-- IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'sg-av-engineers')
-- BEGIN
--     ALTER ROLE [db_datareader] ADD MEMBER [sg-av-engineers]
--     ALTER ROLE [db_datawriter] ADD MEMBER [sg-av-engineers]
--     GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[metadata] TO [sg-av-engineers]
--     GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[instructions] TO [sg-av-engineers]
--     GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[log] TO [sg-av-engineers]
-- END
-- GO